---

- set_fact:
    m_user:
      database: "{{ mongodb_db.name }}"
      name: "{{ mongodb_db.user }}"
      password: "{{ mongodb_db.password }}"
      roles: "{{ mongodb_db.roles|d('readWrite') }}"

- name: merge previously defined mongodb_users with new m_user
  set_fact:
    mongodb_users: "{{ (mongodb_users|d([]))|list_append(m_user) }}"
