---

- set_fact:
    r_admin_tags:
      - administrator
    r_user_tags: "{{ r_user.tags|d([]) }}"

- set_fact:
    r_user_tags: "{{ r_admin_tags|list_append(r_user_tags)|unique|list }}"
  when: r_user.admin|int == 1

# admin user
- rabbitmq_user:
    user: "{{ r_user.name }}"
    password: "{{ r_user.password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: "{{ r_user_tags }}"
    state: present
  when: r_user.admin|int == 1

# non-admin user
- rabbitmq_user:
    user: "{{ r_user.name }}"
    password: "{{ r_user.password }}"
    permissions: "{{ r_user.permissions|d([]) }}"
    tags: "{{ r_user_tags }}"
    state: present
  when: r_user.admin|int != 1
