---

- name: apache.package-debian - add ppa:ondrej/apache2 apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '14AA40EC0831756756D7F66C4F4EA0AAE5267A6C'
    state: present

- name: apache.package-debian - add ppa:ondrej/apache2 repo
  apt_repository:
    repo: ppa:ondrej/apache2
