---

- block:
    - set_fact:
        keep_conf_vhost: []

    - set_fact:
        keep_conf_vhost: "{{ keep_conf_vhost|list_append(('%02d'|format(index|int)) + '-' + vhost.servername + '.conf') }}"
      loop_control:
        loop_var: apache_vhost
      vars:
        index: "{{ apache_vhost.0 }}"
        vhost: "{{ apache_vhost.1 }}"
      with_indexed_items: "{{ apache.vhosts }}"

    - purge_dir:
        dir: "{{ apache_server_root }}/sites-available"
        keep: "{{ keep_conf_vhost }}"
      notify: "{{ notify_apache_list }}"

    - purge_dir:
        dir: "{{ apache_server_root }}/sites-enabled"
        keep: "{{ keep_conf_vhost }}"
      notify: "{{ notify_apache_list }}"

  when: apache_vhost_stat.stat.exists

- block:
    - purge_dir:
        dir: "{{ apache_server_root }}/mods-enabled"
        keep: "{{ (apache.modules | modify_list('(.*)', '\\1.conf')) | list_append(apache.modules | modify_list('(.*)', '\\1.load')) }}"
      notify: "{{ notify_apache_list }}"

  when: apache_mods_stat.stat.exists
