---

- name: apache.vhost - merge user-defined apache vhost data with default
  set_fact:
    _vhost: "{{ _apache_vhost | deep_merge(vhost) }}"

- set_fact:
    index_formatted: "{{ '%02d' | format(index|int) }}"
    servername: "{{ _vhost.servername }}"

- name: apache.vhost - generate apache site config to sites-available
  template:
    src: "{{ role_path }}/templates/apache/vhost.j2"
    dest: "{{ apache_server_root }}/sites-available/{{ index_formatted }}-{{ servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: "{{ notify_apache_list }}"

- name: apache.vhost - create symlink from apache sites-enabled to sites-available
  file:
    src: "{{ apache_server_root }}/sites-available/{{ index_formatted }}-{{ servername }}.conf"
    dest: "{{ apache_server_root }}/sites-enabled/{{ index_formatted }}-{{ servername }}.conf"
    state: link
  notify: "{{ notify_apache_list }}"

- name: apache.vhost - add ports apache site listens on to firewall
  include_tasks: ../firewall_add.yml
  loop_control:
    loop_var: loop_rule
  vars:
    rule:
      protocol: tcp
      port: "{{ loop_rule | regex_replace('[A-Za-z]+[0-9]*') | regex_replace('[\\s*]') | regex_replace('[^\\d ]') }}"
      action: accept
  with_items: "{{ _vhost.port }}"
