---

- set_fact:
    index_formatted: "{{ '%02d'|format(index|int) }}"
    servername: "{{ vhost.servername|d('default') }}"

- template:
    src: "{{ role_path }}/templates/apache/vhost.j2"
    dest: "{{ apache_server_root }}/sites-available/{{ index_formatted }}-{{ servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: "{{ notify_apache_list }}"

- file:
    src: "{{ apache_server_root }}/sites-available/{{ index_formatted }}-{{ servername }}.conf"
    dest: "{{ apache_server_root }}/sites-enabled/{{ index_formatted }}-{{ servername }}.conf"
    state: link
  notify: "{{ notify_apache_list }}"
