---

- name: python.virtualenv - build expected python_virtualenvs item
  set_fact:
    python_virtualenv:
      path: "{{ virtenv.path }}"
      python: "python{{ virtenv.version | regex_replace('python') }}"
    when: virtenv.virtualenv|d(0)|int == 1

- name: python.virtualenv - merge previously defined virtenvs with new virtenv
  set_fact:
    python_virtualenvs: "{{ (python_virtualenvs|d([])) | list_append(python_virtualenv|d([])) }}"
