---

- include_vars: "apache-{{ ansible_os_family|lower }}.yml"

- set_fact:
    apache_version: "{{ apache.settings.version|d(2.4) }}"
    apache_mods_enabled: "{{ apache.modules | modify_list('(.*)', '\\1.load') }}"
    apache_create_vhosts: false
    apache_vhosts: "{{ apache.vhosts }}"
    apache_default_vhost: "{{ apache.settings.default_vhost|d(0) }}"

- set_fact:
    apache_vhosts: "{{ _apache_default_vhost|list_append(apache_vhosts) }}"
  when: apache_default_vhost|int == 1

- include_tasks: "apache/package-{{ ansible_os_family }}.yml"

- include_vars:
    file: "{{ playbook_dir }}/roles/geerlingguy.apache/vars/{{ ansible_os_family }}.yml"

- file:
    path: "{{ apache_logroot }}"
    state: directory
    owner: root
    group: root

- stat:
    path: "{{ apache_server_root }}/sites-available"
  register: apache_vhost_stat

- stat:
    path: "{{ apache_server_root }}/mods-available"
  register: apache_mods_stat

- set_fact:
    notify_apache_list: []

- include_tasks: apache/purge.yml

- include_tasks: apache/vhost.yml
  loop_control:
    loop_var: apache_vhost
  vars:
    index: "{{ apache_vhost.0 }}"
    vhost: "{{ apache_vhost.1 }}"
  with_indexed_items: "{{ apache_vhosts }}"
  when: apache_vhost_stat.stat.exists

- include_role:
    name: geerlingguy.apache

- set_fact:
    notify_apache_list:
      - restart apache

- include_tasks: apache/vhost.yml
  loop_control:
    loop_var: apache_vhost
  vars:
    index: "{{ apache_vhost.0 }}"
    vhost: "{{ apache_vhost.1 }}"
  with_indexed_items: "{{ apache_vhosts }}"
  when: vhost_stat.stat.exists == false

- copy:
    src: "{{ role_path }}/files/webserver_landing.html"
    dest: '/var/www/html/index.html'
    owner: root
    group: root
    mode: 0644
  when: apache_default_vhost|int == 1
  changed_when: False
