---

- name: beanstalkd - set vpeltot.beanstalkd variables
  set_fact:
    beanstalkd_listen_address: "{{ beanstalkd.settings.listenaddress }}"
    beanstalkd_listen_port: "{{ beanstalkd.settings.listenport }}"

- name: beanstalkd - add beanstalkd port to firewall
  include_tasks: firewall_add.yml
  vars:
    rule:
      protocol: tcp
      port: "{{ beanstalkd_listen_port }}"
      action: accept

- name: beanstalkd - include vpeltot.beanstalkd
  include_role:
    name: vpeltot.beanstalkd
