---
# Expected variables:
#   firewall_rules

- name: firewall - define default firewall values
  set_fact:
    iptables_deny_all: true
    iptables_allowed_tcp_ports: []

- name: firewall - set Stouts.iptables variables
  set_fact:
    iptables_raw_rules: "{{ (firewall_rules|d([])) | unique }}"

- name: firewall - include Stouts.iptables
  include_role:
    name: Stouts.iptables
