---
# Expected variables:
#   java

- name: java - java key may not be present in config file
  set_fact:
    java_settings:
      settings: {}

- set_fact:
    java: "{{ java|d({}) | deep_merge(java_settings) }}"

- name: java - configure repo for Java 8.x
  include_tasks: "java/package-{{ ansible_os_family }}.yml"
  when: java.settings.version|d(8) | version_compare('8.0', '>=')

- name: java - include geerlingguy.java
  include_role:
    name: geerlingguy.java
