---

- name: mailhog - set geerlingguy.mailhog variables
  set_fact:
    mailhog_install_dir: "{{ mailhog.settings.path }}"

- name: mailhog - add mailhog ports to firewall
  include_tasks: firewall_add.yml
  vars:
    rule:
      protocol: tcp
      port: "{{ item }}"
      action: accept
  with_items:
    - 1025
    - 8025

- name: mailhog - include geerlingguy.mailhog
  include_role:
    name: geerlingguy.mailhog
