---

- set_fact:
    mysql_root_password: "{{ mariadb.settings.root_password }}"
    mysql_user_password: "{{ mariadb.settings.root_password }}"
    mysql_root_password_update: yes
    mysql_user_password_update: yes
    mysql_databases: "{{ mariadb.databases }}"

- include_tasks: mysql/package/debian-mariadb.yml

- include_tasks: mysql/user.yml
  loop_control:
    loop_var: l_mysql_user
  vars:
    mysql_user: "{{ l_mysql_user }}"
  with_items: "{{ mariadb.users }}"

- include_role:
    name: geerlingguy.mysql

# todo: configure centos support
