---
# Expected variables:
#   mariadb

- name: mariadb - set geerlingguy.mysql variables
  set_fact:
    mysql_root_password_update: yes
    mysql_user_password_update: yes
    mysql_databases: "{{ mariadb.databases|d([]) }}"

- name: mariadb - set geerlingguy.mysql password variables
  set_fact:
    mysql_root_password: "{{ mariadb.settings.root_password }}"
    mysql_user_password: "{{ mariadb.settings.root_password }}"
  no_log: true

- name: mariadb - configure repo
  include_tasks: "mysql/package-{{ ansible_os_family }}-mariadb.yml"

- name: mariadb - create user list
  include_tasks: mysql/user.yml
  loop_control:
    loop_var: l_mysql_user
  vars:
    mysql_user: "{{ l_mysql_user }}"
  with_items: "{{ mariadb.users|d([]) }}"

- name: mariadb - include geerlingguy.mysql
  include_role:
    name: geerlingguy.mysql

# todo: configure centos support
