---
# Expected variables:
#   mongodb

- name: mongodb - include greendayonfire.mongodb default vars
  include_vars:
    file: "{{ playbook_dir }}/roles/greendayonfire.mongodb/defaults/main.yml"

- name: mongodb - set greendayonfire.mongodb variables
  set_fact:
    mongodb_security_authorization: enabled
    mongodb_version: "{{ mongodb.settings.version|d(mongodb_version) }}"
    mongodb_net_bindip: "{{ mongodb.settings.bind_ip|d(mongodb_net_bindip) }}"
    mongodb_net_port: "{{ mongodb.settings.port|d(mongodb_net_port) }}"
    mongodb_root_admin_name: "{{ mongodb.settings.root_admin_user|d(mongodb_root_admin_name) }}"
    mongodb_user_admin_name: "{{ mongodb.settings.user_admin_user|d(mongodb_user_admin_name) }}"

- name: mongodb - set greendayonfire.mongodb password variables
  set_fact:
    mongodb_root_admin_password: "{{ mongodb.settings.root_admin_password }}"
    mongodb_root_backup_password: "{{ mongodb.settings.root_admin_password }}"
    mongodb_user_admin_password: "{{ mongodb.settings.user_admin_password }}"
  no_log: true

- name: mongodb - create database list
  include_tasks: mongodb/database.yml
  loop_control:
    loop_var: l_mongodb_database
  vars:
    mongodb_db: "{{ l_mongodb_database }}"
  with_items: "{{ mongodb.databases|d([]) }}"

- name: mongodb - create security keyfile
  command: "openssl rand -base64 -out {{ mongodb_security_keyfile }} 741"
  args:
    creates: "{{ mongodb_security_keyfile }}"

- name: mongodb - set security keyfile permissions
  file:
    path: "{{ mongodb_security_keyfile }}"
    owner: root
    group: root
    mode: 0644

- name: mongodb - include greendayonfire.mongodb
  include_role:
    name: greendayonfire.mongodb

# todo: configure centos support
