---
# Expected variables:
#   nodejs

- include_vars: "{{ playbook_dir }}/roles/geerlingguy.nodejs/defaults/main.yml"

- name: nodejs - set geerlingguy.nodejs variables
  set_fact:
    nodejs_version: "{{ nodejs.settings.version|d(nodejs_version) }}"
    nodejs_install_npm_user: root

- name: nodejs - construct nodejs_npm_global_packages list
  include_tasks: nodejs/npm_package.yml
  loop_control:
    loop_var: l_npm_package
  vars:
    npm_p: "{{ l_npm_package }}"
  with_items: "{{ nodejs.npm_packages|d([]) }}"

- name: nodejs - include geerlingguy.nodejs
  include_role:
    name: geerlingguy.nodejs
