---

- set_fact:
    python_ppa: ppa:deadsnakes/ppa
    python_versions: "{{ python.versions|json_query('[].version') }}"
    python_install: "{{ python.packages|d([]) | modify_list('@','==') }}"

- include_tasks: python/virtualenv.yml
  loop_control:
    loop_var: python_virtenv
  vars:
    virtenv: "{{ python_virtenv }}"
  with_items: "{{ python.versions|d([]) }}"

- include_role:
    name: Stouts.python

# todo: configure centos support
