---
# Expected variables:
#   rabbitmq

- name: rabbitmq - set Stouts.rabbitmq variables
  set_fact:
    rabbitmq_plugins: "{{ rabbitmq.plugins|d([]) }}"
    rabbitmq_vhosts: "{{ rabbitmq.vhosts|d([]) }}"
    rabbitmq_users: []

- name: rabbitmq - include Stouts.rabbitmq
  include_role:
    name: Stouts.rabbitmq

- name: rabbitmq - add users
  include_tasks: rabbitmq/user.yml
  loop_control:
    loop_var: l_r_user
  vars:
    r_user: "{{ l_r_user }}"
  with_items: "{{ rabbitmq.users|d([]) }}"
