---

- set_fact:
    redis_port: "{{ redis.settings.port|d(6379) }}"

- include_tasks: firewall_add.yml
  vars:
    rule:
      protocol: tcp
      port: "{{ redis_port }}"
      action: accept

- include_role:
    name: geerlingguy.redis

# todo: configure centos support
