---

- include_vars: resolv.yml

- name: resolve - merge user-defined resolv data with default
  set_fact:
    resolv: "{{ _resolv | combine(resolv) }}"

- name: resolve - set ahuffman.resolv variables
  set_fact:
    resolv_nameservers: "{{ resolv.nameservers }}"
    resolv_domain: "{{ resolv.domainname }}"
    resolv_search: "{{ resolv.searchpath }}"

- name: resolve - include ahuffman.resolv
  include_role:
    name: ahuffman.resolv
