---
# Expected variables:
#   ruby

- name: ruby - set rvm_io.ruby variables
  set_fact:
    rvm1_rubies: "{{ ruby.versions|d([]) | json_query('[].version') }}"
    rvm1_bundler_install: false
    rvm1_install_path: /usr/local/rvm
    rvm1_install_flags: '--auto-dotfiles'
    rvm1_user: root

- name: ruby - resort ruby versions list and place default at end of list
  include_tasks: ruby/version.yml
  loop_control:
    loop_var: l_ruby_version
  vars:
    ruby_v: "{{ l_ruby_version }}"
  with_items: "{{ ruby.versions|d([]) }}"

- name: ruby - include rvm_io.ruby
  include_role:
    name: rvm_io.ruby

- name: ruby - install ruby gems
  include_tasks: ruby/gem.yml
  loop_control:
    loop_var: l_ruby_gem
  vars:
    ruby_gem: "{{ l_ruby_gem }}"
  with_items: "{{ ruby.gems|d([]) }}"

# todo: configure centos support
