---
# Expected variables:
#   users - List of users. To add user to a group use the format {USER}:{GROUP}.
#           To assign a user to multiple groups use the format {USER}:{GROUP1}:{GROUP2}

- name: user - create groups from user-defined users list
  include_tasks: group.yml
  loop_control:
    loop_var: l_user_groups
  vars:
    groups_list: "{{ l_user_groups.split(':')[0:] }}"
  with_items: "{{ users }}"

- name: user - create users from user-defined lists
  user:
    name: "{{ item.split(':')[0] }}"
    groups: "{{ item.split(':')[0:] }}"
    append: yes
  with_items: "{{ users }}"
