---

- set_fact:
    ruby_version: "{{ ruby_v.version }}"
    ruby_default: "{{ ruby_v.default|d(0) }}"

- name: merge previously defined ruby_rvms with new ruby_rvm
  set_fact:
    rvm1_rubies: "{{ (rvm1_rubies|d([]))|reject('search', ruby_version)|list }}"
  when: ruby_default|int == 1

- name: place default Ruby version at end of list
  set_fact:
    rvm1_rubies: "{{ rvm1_rubies|list_append(ruby_version) }}"
  when: ruby_default|int == 1
