---

- include_vars: cron.yml

- name: cron.job - merge user-defined cron job data with default
  set_fact:
    _job: "{{ _cron_job | deep_merge(job) }}"

- name: "cron.job - set ENV vars for '{{ _job.name }}' cron"
  cron:
    name: "{{ item.split('=')[0] }}"
    user: "{{ _job.user }}"
    value: "{{ item.split('=')[1:][0] }}"
    env: yes
    cron_file: "/tmp/crontab/{{ _job.user }}"
  with_items: "{{ _job.environment|d([]) }}"

- name: "cron.job - create '{{ _job.name }}' cron"
  cron:
    name: "{{ _job.name }}"
    user: "{{ _job.user }}"
    job: "{{ _job.command }}"
    minute: "{{ (_job.minute == '') | ternary('*', _job.minute) }}"
    hour: "{{ (_job.hour == '') | ternary('*', _job.hour) }}"
    weekday: "{{ (_job.weekday == '') | ternary('*', _job.weekday) }}"
    month: "{{ (_job.month == '') | ternary('*', _job.month) }}"
    day: "{{ (_job.monthday == '') | ternary('*', _job.monthday) }}"
    cron_file: "/tmp/crontab/{{ _job.user }}"

