---

- name: nodejs.npm_package - split out npm package name and version
  set_fact:
    npm_package:
      name: "{{ npm_p.split('@')[0] }}"
      version: "{{ (npm_p.split('@')[1])|d('') }}"

- name: nodejs.npm_package - add npm package to master list
  set_fact:
    nodejs_npm_global_packages: "{{ (nodejs_npm_global_packages|d([])) | list_append(npm_package) }}"
