---

- set_fact:
    p_database:
      name: "{{ psql_database.name }}"
      lc_collate: "{{ psql_database.lc_collate|d('en_US.UTF-8') }}"
      lc_ctype: "{{ psql_database.lc_ctype|d('en_US.UTF-8') }}"
      encoding: "{{ psql_database.encoding|d('UTF-8') }}"
      template: "{{ psql_database.template|d('template0') }}"
      login_host: "{{ psql_database.login_host|d('localhost') }}"
      login_password: "{{ psql_database.login_password|d('') }}"

- name: merge previously defined postgresql_databases with new p_database
  set_fact:
    postgresql_databases: "{{ (postgresql_databases|d([]))|list_append(p_database) }}"
