---

- postgresql_privs:
    database: "{{ psql_privilege.database }}"
    state: "{{ psql_privilege.state|d('present') }}"
    privs: "{{ psql_privilege.privs|d([])|join(',') }}"
    type: "{{ psql_privilege.type|d('database') }}"
    objs: "{{ psql_privilege.objs|d([])|join(',') }}"
    schema: "{{ psql_privilege.schema|d(omit) }}"
    roles: "{{ psql_privilege.roles|d([])|join(',') }}"
    grant_option: "{{ psql_privilege.grant_option|d(omit) }}"
  become: true
  become_user: postgres
